import { Box, Flex, Heading, Link, Stack, Text, useColorModeValue } from '@chakra-ui/react'
import Head from 'next/head'
import CalcForm from '../components/CalcForm'


export default function Home() {
  
  return (
    <Flex
      minH={'100vh'}
      align={'center'}
      justify={'center'}
      bg={useColorModeValue('gray.50', 'gray.800')}>
      <Stack spacing={8} mx={'auto'} maxW={'lg'} py={12} px={6}>
        <Stack align={'center'}>
          <Heading fontSize={'4xl'}>Calcule sua média</Heading>
          <Text fontSize={'lg'} color={'gray.600'}>
            Me acompanhe no <Link color={'blue.400'} target="_blank" href="https://www.linkedin.com/in/devpedrohenrique/">LinkedIn</Link> ✌️
          </Text>
        </Stack>
        <Box
          rounded={'lg'}
          bg={useColorModeValue('white', 'gray.700')}
          boxShadow={'lg'}
          p={8}>
          <Stack spacing={4}>
            <Head>
              <title>IMD Notas</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <CalcForm />
            
          </Stack>
        </Box>
      </Stack>
    </Flex>
  )
}
